version: '3'

services:
  tests:
    build:
      context: .
      dockerfile: test.Dockerfile
    entrypoint: ""
    environment:
      MATRIX_URL: http://tests
      MATRIX_ID: bot
      MATRIX_PW: pw
    volumes:
      - ./:/app
